/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as ApiVideosSearchRouteImport } from './routes/api.videos.search'
import { Route as ApiPublicHooksSyncYoutubeRouteImport } from './routes/api/public/hooks/sync-youtube'
import { Route as ApiPublicHooksTestVideosRouteImport } from './routes/api/public/hooks/test-videos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ApiVideosSearchRoute = ApiVideosSearchRouteImport.update({
  id: '/api/videos/search',
  path: '/api/videos/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncYoutubeRoute =
  ApiPublicHooksSyncYoutubeRouteImport.update({
    id: '/api/public/hooks/sync-youtube',
    path: '/api/public/hooks/sync-youtube',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestVideosRoute =
  ApiPublicHooksTestVideosRouteImport.update({
    id: '/api/public/hooks/test-videos',
    path: '/api/public/hooks/test-videos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/api/videos/search': typeof ApiVideosSearchRoute
  '/api/public/hooks/sync-youtube': typeof ApiPublicHooksSyncYoutubeRoute
  '/api/public/hooks/test-videos': typeof ApiPublicHooksTestVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/api/videos/search': typeof ApiVideosSearchRoute
  '/api/public/hooks/sync-youtube': typeof ApiPublicHooksSyncYoutubeRoute
  '/api/public/hooks/test-videos': typeof ApiPublicHooksTestVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/api/videos/search': typeof ApiVideosSearchRoute
  '/api/public/hooks/sync-youtube': typeof ApiPublicHooksSyncYoutubeRoute
  '/api/public/hooks/test-videos': typeof ApiPublicHooksTestVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/profile'
    | '/app/'
    | '/api/videos/search'
    | '/api/public/hooks/sync-youtube'
    | '/api/public/hooks/test-videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/profile'
    | '/app'
    | '/api/videos/search'
    | '/api/public/hooks/sync-youtube'
    | '/api/public/hooks/test-videos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/profile'
    | '/app/'
    | '/api/videos/search'
    | '/api/public/hooks/sync-youtube'
    | '/api/public/hooks/test-videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiVideosSearchRoute: typeof ApiVideosSearchRoute
  ApiPublicHooksSyncYoutubeRoute: typeof ApiPublicHooksSyncYoutubeRoute
  ApiPublicHooksTestVideosRoute: typeof ApiPublicHooksTestVideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/videos/search': {
      id: '/api/videos/search'
      path: '/api/videos/search'
      fullPath: '/api/videos/search'
      preLoaderRoute: typeof ApiVideosSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-youtube': {
      id: '/api/public/hooks/sync-youtube'
      path: '/api/public/hooks/sync-youtube'
      fullPath: '/api/public/hooks/sync-youtube'
      preLoaderRoute: typeof ApiPublicHooksSyncYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-videos': {
      id: '/api/public/hooks/test-videos'
      path: '/api/public/hooks/test-videos'
      fullPath: '/api/public/hooks/test-videos'
      preLoaderRoute: typeof ApiPublicHooksTestVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiVideosSearchRoute: ApiVideosSearchRoute,
  ApiPublicHooksSyncYoutubeRoute: ApiPublicHooksSyncYoutubeRoute,
  ApiPublicHooksTestVideosRoute: ApiPublicHooksTestVideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
